function queryElement<T extends Element>(selector: string): T {
  const element = document.querySelector<T>(selector);
  if (!element) {
    throw new Error(`Missing required element: ${selector}`);
  }

  return element;
}

export function getPresentationElements() {
  return {
    html: document.documentElement,
    titleInput: queryElement<HTMLInputElement>("#title-input"),
    editorShell: queryElement<HTMLElement>(".editor-shell"),
    editor: queryElement<HTMLTextAreaElement>("#editor"),
    prettyEditor: queryElement<HTMLElement>("#pretty-editor"),
    printPreview: queryElement<HTMLElement>("#print-preview"),
    wordCount: queryElement<HTMLElement>("#word-count"),
    readingTime: queryElement<HTMLElement>("#reading-time"),
    toast: queryElement<HTMLElement>("#toast"),
    newDocumentButton: queryElement<HTMLButtonElement>("#new-doc-btn"),
    libraryButton: queryElement<HTMLButtonElement>("#library-btn"),
    outlineButton: queryElement<HTMLButtonElement>("#outline-btn"),
    themeButton: queryElement<HTMLButtonElement>("#theme-btn"),
    themeIcon: queryElement<SVGUseElement>("#theme-icon"),
    libraryDialog: queryElement<HTMLDialogElement>("#library-dialog"),
    outlineDialog: queryElement<HTMLDialogElement>("#outline-dialog"),
    settingsDialog: queryElement<HTMLDialogElement>("#settings-dialog"),
    historyDialog: queryElement<HTMLDialogElement>("#history-dialog"),
    historyPreviewDialog: queryElement<HTMLDialogElement>("#history-preview-dialog"),
    dataSafetyDialog: queryElement<HTMLDialogElement>("#data-safety-dialog"),
    backupReviewDialog: queryElement<HTMLDialogElement>("#backup-review-dialog"),
    findDialog: queryElement<HTMLDialogElement>("#find-dialog"),
    linkDialog: queryElement<HTMLDialogElement>("#link-dialog"),
    tableDialog: queryElement<HTMLDialogElement>("#table-dialog"),
    imageDialog: queryElement<HTMLDialogElement>("#image-dialog"),
    shortcutsDialog: queryElement<HTMLDialogElement>("#shortcuts-dialog"),
    commandDialog: queryElement<HTMLDialogElement>("#command-dialog"),
    commandInput: queryElement<HTMLInputElement>("#command-input"),
    commandList: queryElement<HTMLElement>("#command-list"),
    librarySearch: queryElement<HTMLInputElement>("#library-search"),
    documentList: queryElement<HTMLElement>("#document-list"),
    tagFilterList: queryElement<HTMLElement>("#tag-filter-list"),
    outlineList: queryElement<HTMLElement>("#outline-list"),
    linkList: queryElement<HTMLElement>("#link-list"),
    backlinkList: queryElement<HTMLElement>("#backlink-list"),
    historyList: queryElement<HTMLElement>("#history-list"),
    historyPreviewSummary: queryElement<HTMLElement>("#history-preview-summary"),
    historyPreviewContent: queryElement<HTMLElement>("#history-preview-content"),
    restorePreviewButton: queryElement<HTMLButtonElement>("#restore-preview-btn"),
    dataSafetySummary: queryElement<HTMLElement>("#data-safety-summary"),
    persistStorageButton: queryElement<HTMLButtonElement>("#persist-storage-btn"),
    exportAllMarkdownButton: queryElement<HTMLButtonElement>("#export-all-md-btn"),
    dataBackupButton: queryElement<HTMLButtonElement>("#data-backup-btn"),
    backupReviewSummary: queryElement<HTMLElement>("#backup-review-summary"),
    backupAppendButton: queryElement<HTMLButtonElement>("#backup-append-btn"),
    backupReplaceButton: queryElement<HTMLButtonElement>("#backup-replace-btn"),
    findInput: queryElement<HTMLInputElement>("#find-input"),
    replaceInput: queryElement<HTMLInputElement>("#replace-input"),
    replaceNextButton: queryElement<HTMLButtonElement>("#replace-next-btn"),
    replaceAllButton: queryElement<HTMLButtonElement>("#replace-all-btn"),
    findList: queryElement<HTMLElement>("#find-list"),
    linkLabelInput: queryElement<HTMLInputElement>("#link-label-input"),
    linkKindSelect: queryElement<HTMLSelectElement>("#link-kind-select"),
    linkTargetInput: queryElement<HTMLInputElement>("#link-target-input"),
    linkTargetOptions: queryElement<HTMLDataListElement>("#link-target-options"),
    insertLinkButton: queryElement<HTMLButtonElement>("#insert-link-btn"),
    tableColumnsInput: queryElement<HTMLInputElement>("#table-columns-input"),
    tableRowsInput: queryElement<HTMLInputElement>("#table-rows-input"),
    insertTableButton: queryElement<HTMLButtonElement>("#insert-table-btn"),
    imageSourceInput: queryElement<HTMLInputElement>("#image-source-input"),
    imageAltInput: queryElement<HTMLInputElement>("#image-alt-input"),
    imageCaptionInput: queryElement<HTMLInputElement>("#image-caption-input"),
    imageLayoutSelect: queryElement<HTMLSelectElement>("#image-layout-select"),
    insertImageButton: queryElement<HTMLButtonElement>("#insert-image-btn"),
    importMarkdownButton: queryElement<HTMLButtonElement>("#import-md-btn"),
    importBackupButton: queryElement<HTMLButtonElement>("#import-backup-btn"),
    backupButton: queryElement<HTMLButtonElement>("#backup-btn"),
    fileInput: queryElement<HTMLInputElement>("#file-input"),
    backupInput: queryElement<HTMLInputElement>("#backup-input"),
    fontSelect: queryElement<HTMLSelectElement>("#font-select"),
    fontScale: queryElement<HTMLInputElement>("#font-scale"),
    autosaveToggle: queryElement<HTMLInputElement>("#autosave-toggle"),
    sourceModeToggle: queryElement<HTMLInputElement>("#source-mode-toggle"),
  };
}

export type PresentationElements = ReturnType<typeof getPresentationElements>;
